//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Address
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual string Company
		{get;set;}
	
		public virtual string Department
		{get;set;}
	
		public virtual string Floor
		{get;set;}
	
		public virtual string StreetNumber
		{get;set;}
	
		public virtual string BuildingName
		{get;set;}
	
		public virtual string BoxNumber
		{get;set;}
	
		public virtual string Street
		{get;set;}
	
		public virtual string Locality
		{get;set;}
	
		public virtual string City
		{get;set;}
	
		public virtual string GoverningDistrict
		{get;set;}
	
		public virtual string PostalArea
		{get;set;}
	
		public virtual string Country
		{get;set;}
	
		public virtual int CountryIso
		{get;set;}
	
	}
}