//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Address
	{
		public Guid Id
		{get;set;}
	
		public string Company
		{get;set;}
	
		public string Department
		{get;set;}
	
		public string Floor
		{get;set;}
	
		public string StreetNumber
		{get;set;}
	
		public string BuildingName
		{get;set;}
	
		public string BoxNumber
		{get;set;}
	
		public string Street
		{get;set;}
	
		public string Locality
		{get;set;}
	
		public string City
		{get;set;}
	
		public string GoverningDistrict
		{get;set;}
	
		public string PostalArea
		{get;set;}
	
		public string Country
		{get;set;}
	
		public int CountryIso
		{get;set;}
	
	}
}