//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Area
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual string Name
		{get;set;}
	
		public virtual string Description
		{get;set;}
	
		public virtual string Boundary
		{get;set;}
	
		public virtual string Format
		{get;set;}
	
	}
}