//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Area
	{
		public Guid Id
		{get;set;}
	
		public string Name
		{get;set;}
	
		public string Description
		{get;set;}
	
		public string Boundary
		{get;set;}
	
		public string Format
		{get;set;}
	
	}
}