//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Booking
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual Guid? QuoteId
		{get;set;}
	
		public virtual string PaymentMethod
		{get;set;}
	
		public virtual int Currency
		{get;set;}
	
		public virtual List<BookingShipment> BookingShipments
		{get;set;}
	
	}
}