//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class BookingShipment
	{
		public Shipment Shipment
		{get;set;}
	
		public Guid ServiceId
		{get;set;}
	
	}
}