//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Booking
	{
		public Guid Id
		{get;set;}
	
		public Guid QuoteId
		{get;set;}
	
		public string PaymentMethod
		{get;set;}
	
		public int Currency
		{get;set;}
	
		public List<BookingShipment> BookingShipments
		{get;set;}
	
	}
}