//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Carrier
	{
		public Guid Id
		{get;set;}
	
		public string Name
		{get;set;}
	
		public bool Private
		{get;set;}
	
		public bool Editable
		{get;set;}
	
		public List<Service> Services
		{get;set;}
	
	}
}