//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Contact
	{
		public Guid Id
		{get;set;}
	
		public Address Address
		{get;set;}
	
		public string FirstName
		{get;set;}
	
		public string MiddleNames
		{get;set;}
	
		public string Surname
		{get;set;}
	
		public string PhoneNumber
		{get;set;}
	
		public string MobileNumber
		{get;set;}
	
		public string Email
		{get;set;}
	
	}
}