//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Contact
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual Address Address
		{get;set;}
	
		public virtual string FirstName
		{get;set;}
	
		public virtual string MiddleNames
		{get;set;}
	
		public virtual string Surname
		{get;set;}
	
		public virtual string PhoneNumber
		{get;set;}
	
		public virtual string MobileNumber
		{get;set;}
	
		public virtual string Email
		{get;set;}
	
	}
}