//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Country
	{
		public virtual int Iso
		{get;set;}
	
		public virtual string Name
		{get;set;}
	
	}
}