//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Dimension
	{
		public virtual int Height
		{get;set;}
	
		public virtual int Length
		{get;set;}
	
		public virtual int Width
		{get;set;}
	
	}
}