//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Dimension
	{
		public int Height
		{get;set;}
	
		public int Length
		{get;set;}
	
		public int Width
		{get;set;}
	
	}
}