//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Markup
	{
		public Guid Id
		{get;set;}
	
		public decimal Decimal
		{get;set;}
	
		public decimal Amount
		{get;set;}
	
		public int Currency
		{get;set;}
	
	}
}