//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Markup
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual decimal Decimal
		{get;set;}
	
		public virtual decimal Amount
		{get;set;}
	
		public virtual int Currency
		{get;set;}
	
	}
}