//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Parcel
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual string Reference
		{get;set;}
	
		public virtual int Weight
		{get;set;}
	
		public virtual Dimension Size
		{get;set;}
	
		public virtual int CommodityCode
		{get;set;}
	
		public virtual string Description
		{get;set;}
	
		public virtual decimal Value
		{get;set;}
	
		public virtual int Currency
		{get;set;}
	
	}
}