//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Parcel
	{
		public Guid Id
		{get;set;}
	
		public string Reference
		{get;set;}
	
		public int Weight
		{get;set;}
	
		public Dimension Size
		{get;set;}
	
		public int CommodityCode
		{get;set;}
	
		public string Description
		{get;set;}
	
		public decimal Value
		{get;set;}
	
		public int Currency
		{get;set;}
	
	}
}