//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Query
	{
		public Guid Id
		{get;set;}
	
		public int Currency
		{get;set;}
	
		public List<Shipment> Shipments
		{get;set;}
	
	}
}