//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Query
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual int Currency
		{get;set;}
	
		public virtual List<Shipment> Shipments
		{get;set;}
	
	}
}