//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Quote
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual Guid? QueryId
		{get;set;}
	
		public virtual int Currency
		{get;set;}
	
		public virtual List<QuoteShipment> QuoteShipments
		{get;set;}
	
	}
}