//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Quote
	{
		public Guid Id
		{get;set;}
	
		public Guid QueryId
		{get;set;}
	
		public int Currency
		{get;set;}
	
		public List<QuoteShipment> QuoteShipments
		{get;set;}
	
	}
}