//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Rate
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual DateTime? Start
		{get;set;}
	
		public virtual DateTime? End
		{get;set;}
	
		public virtual int MinWeight
		{get;set;}
	
		public virtual int MaxWeight
		{get;set;}
	
		public virtual int MinVolume
		{get;set;}
	
		public virtual int MaxVolume
		{get;set;}
	
		public virtual int MinLength
		{get;set;}
	
		public virtual int MaxLength
		{get;set;}
	
		public virtual int MinWidth
		{get;set;}
	
		public virtual int MaxWidth
		{get;set;}
	
		public virtual int MinHeight
		{get;set;}
	
		public virtual int MaxHeight
		{get;set;}
	
		public virtual int MinQuantity
		{get;set;}
	
		public virtual int MaxQuantity
		{get;set;}
	
		public virtual decimal WeightRate
		{get;set;}
	
		public virtual decimal ItemRate
		{get;set;}
	
		public virtual int Currency
		{get;set;}
	
	}
}