//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Receipt
	{
		public Guid Id
		{get;set;}
	
		public Guid BookingId
		{get;set;}
	
		public int Currency
		{get;set;}
	
		public string PaymentUrl
		{get;set;}
	
		public DateTime? Paid
		{get;set;}
	
		public List<ReceiptItem> ReceiptItems
		{get;set;}
	
	}
}