//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Receipt
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual Guid? BookingId
		{get;set;}
	
		public virtual int Currency
		{get;set;}
	
		public virtual string PaymentUrl
		{get;set;}
	
		public virtual DateTime? Paid
		{get;set;}
	
		public virtual List<ReceiptItem> ReceiptItems
		{get;set;}
	
	}
}