//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class ReceiptItem
	{
		public Guid ShipmentId
		{get;set;}
	
		public decimal Cost
		{get;set;}
	
		public Service Service
		{get;set;}
	
		public bool Vat
		{get;set;}
	
	}
}