//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Route
	{
		public Guid Id
		{get;set;}
	
		public Area Origin
		{get;set;}
	
		public Area Destination
		{get;set;}
	
		public int MinDays
		{get;set;}
	
		public int MaxDays
		{get;set;}
	
		public int CollectionTime
		{get;set;}
	
	}
}