//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Route
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual Area Origin
		{get;set;}
	
		public virtual Area Destination
		{get;set;}
	
		public virtual int MinDays
		{get;set;}
	
		public virtual int MaxDays
		{get;set;}
	
		public virtual int CollectionTime
		{get;set;}
	
	}
}