//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Service
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual string Name
		{get;set;}
	
		public virtual string Transport
		{get;set;}
	
		public virtual bool Tracked
		{get;set;}
	
		public virtual bool Volumetric
		{get;set;}
	
		public virtual bool PrintLabels
		{get;set;}
	
		public virtual string Description
		{get;set;}
	
		public virtual string Information
		{get;set;}
	
		public virtual List<Route> Routes
		{get;set;}
	
	}
}