//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Service
	{
		public Guid Id
		{get;set;}
	
		public string Name
		{get;set;}
	
		public string Transport
		{get;set;}
	
		public bool Tracked
		{get;set;}
	
		public bool Volumetric
		{get;set;}
	
		public bool PrintLabels
		{get;set;}
	
		public string Description
		{get;set;}
	
		public string Information
		{get;set;}
	
		public List<Route> Routes
		{get;set;}
	
	}
}