//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Setting
	{
		public string Key
		{get;set;}
	
		public string Value
		{get;set;}
	
		public string RegEx
		{get;set;}
	
	}
}