//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Shipment
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual Contact Sender
		{get;set;}
	
		public virtual Contact Recipient
		{get;set;}
	
		public virtual List<Parcel> Parcels
		{get;set;}
	
		public virtual string Reference
		{get;set;}
	
		public virtual DateTime? Collection
		{get;set;}
	
		public virtual string Instructions
		{get;set;}
	
		public virtual bool Insured
		{get;set;}
	
		public virtual DateTime? Cancelled
		{get;set;}
	
	}
}