//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Shipment
	{
		public Guid Id
		{get;set;}
	
		public Contact Sender
		{get;set;}
	
		public Contact Recipient
		{get;set;}
	
		public List<Parcel> Parcels
		{get;set;}
	
		public string Reference
		{get;set;}
	
		public DateTime? Collection
		{get;set;}
	
		public string Instructions
		{get;set;}
	
		public bool Insured
		{get;set;}
	
		public DateTime? Cancelled
		{get;set;}
	
	}
}