//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Status
	{
		public Guid Id
		{get;set;}
	
		public string Type
		{get;set;}
	
		public DateTime? Date
		{get;set;}
	
		public string Message
		{get;set;}
	
	}
}