//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Status
	{
		public virtual Guid? Id
		{get;set;}
	
		public virtual string Type
		{get;set;}
	
		public virtual DateTime? Date
		{get;set;}
	
		public virtual string Message
		{get;set;}
	
	}
}